data:
  type: cell
  source: ctrl
  target: stim
  condition: condition
  path: datasets/single_perturb/kang_raw.h5ad

dataloader:
    batch_size: 256
    shuffle: true

datasplit:
    groupby: condition 
    # name: train_test
    # holdout: 101
    # key: sample_id
    # mode: ood
    test_size: 0.05
    random_state: 0